name: variant
version: 1.3.6
description: Roslin Variant Pipeline v1.3.6
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 1.0.0
      max: 1.0.0
  cmo:
    version: 1.9.3
    install-path: /ifs/work/pi/cmo_package_archive/
