name: variant
root: /vagrant/roslin-pipelines/
version: 2.6.0
description: Roslin Variant Pipeline v2.6.0
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /tmp
    - /srv
    - /vagrant
env:
  TOIL_LSF_ARGS: '-S 1 -W 168:00'
  TMPDIR: /tmp
  TMP: /tmp
dependencies:
  core:
    version:
      min: 2.1.2
      max: 2.1.2
  cmo:
    version: 1.9.13
    source: github:https://github.com/mskcc/cmo
  singularity:
    version: 3.4.1
    source: path:/usr/bin/singularity
  toil:
    version: 3.19.0
    source: github:https://github.com/mskcc/toil
test:
  root: /vagrant/roslin-test/
  data_path: /vagrant/roslin-test/roslin_variant_version_2.5.0_test_data.tar.gz
  data_url: https://s3.us-east-2.amazonaws.com/roslindata/roslin_variant_version_2.5.0_test_data.tar.gz
  batchsystem: singleMachine
  cwlBatchsystem: singleMachine
  useDocker: False
  dockerRegistry: None
  tempDir: /tmp
  runArgs: '--test-mode'
  env:
    TOIL_LSF_ARGS: '-S 1'
build:
  buildDocker: False
  buildSingularity: True
  buildCache: /vagrant/build-cache
  dockerRegistry: 'mskcc'
  dockerPush: False
  useVagrant: False
  installCore: True
  buildThreads: 2
